/*
package com.navaco.service.gateway.service;

import com.navaco.service.gateway.model.DailySituation;
import com.navaco.service.gateway.model.IDailySituationServiceInsertSinapExceptionFaultFaultMessage;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

*/
/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-08-21T14:06:07.680+04:30
 * Generated source version: 3.3.2
 *//*

@WebService(serviceName = "DailySituationService",
        targetNamespace = "http://tempuri.org/",
        portName = "BasicHttpBinding_IDailySituationService")
public interface IDailySituationService {

    @WebMethod()
    @WebResult(name = "InsertResult")
    public String insert(@WebParam(name = "dailySituation") DailySituation dailySituation)
            throws IDailySituationServiceInsertSinapExceptionFaultFaultMessage;

    @WebMethod()
    @WebResult(name = "GetFirstResult")
    public DailySituation getFirst();
}
*/
