
package com.navaco.service.gateway.model;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.2
 * 2019-08-21T14:06:07.680+04:30
 * Generated source version: 3.3.2
 */

@WebFault(name = "SinapException", targetNamespace = "http://schemas.datacontract.org/2004/07/DailySituationServiceLibrary.Exception")
public class IDailySituationServiceInsertSinapExceptionFaultFaultMessage extends Exception {

    private SinapException sinapException;

    public IDailySituationServiceInsertSinapExceptionFaultFaultMessage() {
        super();
    }

    public IDailySituationServiceInsertSinapExceptionFaultFaultMessage(String message) {
        super(message);
    }

    public IDailySituationServiceInsertSinapExceptionFaultFaultMessage(String message, Throwable cause) {
        super(message, cause);
    }

    public IDailySituationServiceInsertSinapExceptionFaultFaultMessage(String message, SinapException sinapException) {
        super(message);
        this.sinapException = sinapException;
    }

    public IDailySituationServiceInsertSinapExceptionFaultFaultMessage(String message, SinapException sinapException, Throwable cause) {
        super(message, cause);
        this.sinapException = sinapException;
    }

    public SinapException getFaultInfo() {
        return this.sinapException;
    }
}
